language: emacs-lisp
dist: precise
sudo: required
cache: apt
before_install:
  - sudo apt-get install -y nodejs
  - curl -fsSkL https://gist.githubusercontent.com/NicolasPetton/f4eafee84499580eb6a8c5706fec925b/raw > travis.sh && source ./travis.sh
  - cask
install:
  - cask install
script:
  - emacs --version
  - ./run-lint.sh
  - ./run-tests.sh
